apiVersion: v1
kind: Service
metadata:
  name: helloworld-store-2
  annotations:
    configmanagement.gke.io/cluster-selector: "selector-store-2"
  labels:
    app: helloworld-store-2
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: helloworld-store-2
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-store-2
  annotations:
    configmanagement.gke.io/cluster-selector: "selector-store-2"
  labels:
    app: helloworld-store-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-store-2
  template:
    metadata:
      labels:
        app: helloworld-store-2
    spec:
      containers:
      - name: helloworld
        image: signalsciences/example-helloworld:latest
        imagePullPolicy: IfNotPresent
        args:
        # Address for the app to listen on
        - localhost:8000
        ports:
        - containerPort: 8000