kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: selector-another
spec:
  selector:
    matchExpressions:
      - key: state
        operator: In
        values:
        - ak